# Generated by Django 5.1.1 on 2024-09-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybuyra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.TextField(verbose_name='Клиент'),
        ),
    ]
