# Generated by Django 5.1 on 2024-10-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybuyra', '0002_remove_review_customer_remove_shoppingcart_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='models', verbose_name='Изображение'),
        ),
    ]
