# Generated by Django 5.1 on 2024-10-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybuyra', '0003_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='products', verbose_name='Изображение'),
        ),
    ]
