# Generated by Django 5.1 on 2024-10-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capybuyra', '0006_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
