# Generated by Django 5.1 on 2024-11-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybuyra', '0009_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='sum',
        ),
        migrations.AddField(
            model_name='productshoppingcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
