# Generated by Django 5.1 on 2024-12-06 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybuyra', '0011_alter_productshoppingcart_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshoppingcart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='capybuyra.product'),
        ),
        migrations.AlterField(
            model_name='productshoppingcart',
            name='shopping_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='capybuyra.shoppingcart'),
        ),
    ]
